apiVersion: apps/v1
#
kind: Deployment
metadata:
  name: sample-deployment-rollingupdate
spec:
  strategy:
    #
    type: RollingUpdate
    rollingUpdate:
      # こちらは値は0にできない
      maxUnavailable: 2
      # こちらは1しか設定できない
      # maxSurge: 1
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx-container
