apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip
spec:
  # 
  type: ClusterIP
  ports:
    # http用のport
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  # sample-deployment.yamlのlabelと合わせる
  selector:
    app: sample-app