apiVersion: v1
kind: Service
metadata:
  name: sample-lb-fw
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector:
    app: sample-app
  # 接続を許可する送信元IPアドレスの範囲
  loadBalancerSourceRanges:
  - 10.0.0.0/8