apiVersion: v1
kind: Pod
metadata:
  name: sample-hostaliases
spec:
  containers:
    - image: nginx:1.12
      name: nginx-container
  hostAliases: # hostの項目を追加
    - ip: 8.8.8.8
      hostnames:
        - google-dns
        - google-public-dns