apiVersion: v1
kind: Service
metadata:
  name: sample-nodeport
spec:
  # NodePortを設定する
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      # ClusterIpで受け付けるPort番号
      port: 8080
      # 転送先のコンテナのPort番号
      targetPort: 80
      # 全Kubernetes Nodeで受け付けるPort番号を指定(指定範囲：30000～32767)
      nodePort: 30080
  selector:
    app: sample-app