apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      # ClusterIPで受け付けるPost番号
      port: 8080
      # 転送先のコンテナのPort番号
      targetPort: 80
  selector:
    app: sample-app