apiVersion: v1
kind: Service
metadata:
  name: sample-externalip
spec:
  type: ClusterIP
  # Kubernetes NodeのIPアドレス
  externalIPs:
    - 10.240.0.7
    - 10.240.0.8
  ports:
    - name: "http-port"
      protocol: "TCP"
      # ClusterIPで受け付けるPost番号
      port: 8080
      # 転送先のコンテナのPort番号
      targetPort: 80
  selector:
    app: sample-app