apiVersion: apps/v1
# 
kind: StatefulSet
metadata:
  name: sample-statefulset-ondelete
spec:
  updateStrategy:
    # OnDeleteを設定。ここ以外設定する箇所はない。
    type: OnDelete
  serviceName: sample-statefulset-ondelete
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12