apiVersion: batch/v1
kind: Job
metadata:
  name: sample-paralleljob
spec:
  # 終了条件
  completions: 10
  # 並列の指定
  parallelism: 2
  # 失敗を許容する回数
  backoffLimit: 10
  template:
    metadata:
      name: sleep-job
    spec:
      containers:
      - name: sleep-container
        image: centos:6
        command: ["sleep"]
        args: ["30"]
      restartPolicy: Never
# 2並列で実行し、10回成功したら終了するJobの例です。またbackoffLimitは、失敗を許容する回数です。